services:

  postgres:
    image: postgres:17

    environment:
      POSTGRES_DB: adiministror
      POSTGRES_USER: administror
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U administror -d adiministror"]
      interval: 5s
      timeout: 5s
      retries: 10


  app:
    build: .

    ports:
      - "8083:8083"

    environment:
      SERVER_PORT: 8083

      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/adiministror
      SPRING_DATASOURCE_USERNAME: administror
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}

    depends_on:
      postgres:
        condition: service_healthy


volumes:
  postgres_data: